# Generated by Django 3.2.5 on 2022-06-15 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot', models.CharField(max_length=10, unique=True)),
                ('arrival_date', models.DateTimeField()),
                ('departure_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='GramStain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('completion_time', models.DateTimeField()),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=256)),
                ('technician_name', models.CharField(max_length=256)),
                ('colony_count', models.PositiveIntegerField()),
                ('organism_discription', models.TextField(max_length=256)),
                ('gram_stain_result', models.BooleanField()),
                ('lot_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lot_number', to='pteforms.lots')),
            ],
        ),
    ]
