# Generated by Django 3.2.5 on 2022-06-24 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0001_initial'),
        ('pteforms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gramstain',
            options={'ordering': ['-start_time']},
        ),
        migrations.AlterField(
            model_name='gramstain',
            name='lot_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gramstainform', to='lots.lot'),
        ),
        migrations.DeleteModel(
            name='Lots',
        ),
    ]
