# Generated by Django 3.2.5 on 2022-06-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(max_length=10, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('harvest_size', models.DecimalField(decimal_places=2, max_digits=3)),
                ('date_shipped', models.DateField()),
                ('date_received', models.DateField()),
            ],
            options={
                'ordering': ['lot_number'],
            },
        ),
    ]
